## Первая практика: проверка свойств бинарных отношений

Свойства:
- рефлексивность
- антирефлексивность
- симметричность
- антисимметричность
- транзитивность
- линейность

In [1]:
def check_reflexivity(matrix):
    for i in range(len(matrix)):
        for j in range(len(matrix[i])):
            if i == j and matrix[i][j] == 0:
                return False
    return True

def check_antireflexivity(matrix):
    for i in range(len(matrix)):
        for j in range(len(matrix[i])):
            if i == j and matrix[i][j] == 1:
                return False
    return True

def check_symmetry(matrix):
    for i in range(len(matrix)):
        for j in range(len(matrix[i])):
            if matrix[i][j] == 1 and matrix[j][i] == 0:
                return False
    return True

def check_antisymmetry(matrix):
    for i in range(len(matrix)):
        for j in range(len(matrix[i])):
            if i != j and matrix[i][j] == 1 and matrix[j][i] == 1:
                return False
    return True

def check_transitivity(matrix):
    # a = i
    # b = j
    # c = k
    for i in range(len(matrix)):
        for j in range(len(matrix[i])):
            if matrix[i][j] == 1: # есть aRb
                for k in range(len(matrix[j])):
                    if matrix[j][k] == 1 and matrix[i][k] == 0: # есть bRc, но нет aRc
                        return False # противоречие, т.к. должно быть для всех a,b,c
    return True

def check_linearity(matrix):
    for i in range(len(matrix)):
        for j in range(len(matrix[i])):
            if i != j and matrix[i][j] == 0 and matrix[j][i] == 0:
                return False
    return True

In [2]:
import numpy as np

n = 7 # число вершин графа
A = [(1, 2), (2, 1), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7)]
B = np.zeros((n, n)) # матрица смежности

# заполняем матрицу смежности
for tup in A:
    B[tup[0] - 1][tup[1] - 1] = 1 # -1 для корректной индексации (в python нумерация с 0)

In [3]:
matrix = B

print("Исходная матрица")
print(matrix)

print("Выполняются свойства")
print(f"Рефлексивность: {check_reflexivity(matrix)}")
print(f"Антирефлексивность: {check_antireflexivity(matrix)}")
print(f"Симметричность: {check_symmetry(matrix)}")
print(f"Антисимметричность: {check_antisymmetry(matrix)}")
print(f"Транзитивность: {check_transitivity(matrix)}")
print(f"Линейность: {check_linearity(matrix)}")

Исходная матрица
[[1. 1. 0. 0. 0. 0. 0.]
 [1. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1.]]
Выполняются свойства
Рефлексивность: True
Антирефлексивность: False
Симметричность: True
Антисимметричность: False
Транзитивность: True
Линейность: False


Проверка свойств для случайной матрицы

In [4]:
def check_properties_for_random_matrix(n): # n - количество вершин
    matrix = np.random.randint(0, 2, (n, n))
    print("Исходная матрица")
    print(matrix)

    print("Выполняются свойства")
    print(f"Рефлексивность: {check_reflexivity(matrix)}")
    print(f"Антирефлексивность: {check_antireflexivity(matrix)}")
    print(f"Симметричность: {check_symmetry(matrix)}")
    print(f"Антисимметричность: {check_antisymmetry(matrix)}")
    print(f"Транзитивность: {check_transitivity(matrix)}")
    print(f"Линейность: {check_linearity(matrix)}")

In [5]:
check_properties_for_random_matrix(8)

Исходная матрица
[[0 1 0 1 0 1 1 1]
 [0 0 1 0 0 1 1 0]
 [1 1 0 1 1 1 0 0]
 [0 1 0 1 1 1 0 1]
 [1 1 0 1 1 0 0 0]
 [1 1 1 1 1 1 0 0]
 [0 0 0 0 1 1 0 0]
 [1 1 1 1 0 1 1 0]]
Выполняются свойства
Рефлексивность: False
Антирефлексивность: False
Симметричность: False
Антисимметричность: False
Транзитивность: False
Линейность: False
